### PR TITLE
Pull request challange - small improvements

### PR DESCRIPTION
**Pull request by happy-barney**

### CODE REVIEW

**Review by Tux — APPROVED** [review]
Will be in. Thank you

**Review by Tux — COMMENTED** [review]
Rejected. This is not the same. No objections to using first, but first does not remove the argument from the list

**Comment by Tux** [comment]
1. Typoes: thank you, applied and pushed
2. List::Util. Will have to think about that one. It is elegant, but does not do the same as the original code. The original code removes the file argument from the list. The list is later used in the last call, so that removal is vital.
3. Support input option: I like it. Applied and pushed
4. Perl version. That needs a lot more testing. I had something similar in before, but something broke, so there will be or might have been situations where that didn't work
5. No new tests?

Thanks for your interest

**Comment by happy-barney** [comment]
two commits applied, two no so good

**Comment by Tux** [comment]
@happy-barney will there be a follow-up or shall I just close this issue?

**Pull request closed without merging**
