### PR TITLE
Pod::Usage in xls2csv

### PR DESCRIPTION
**Pull request by happy-barney**

### CODE REVIEW

**Comment by happy-barney** [comment]
Example on one file. If you'll like it, I'll adapt other examples as well.

**Comment by Tux** [comment]
I applied it locally to see what happens. Hmm.

1. The pod should be at the end of the file IMHO (after `__END__`)
2. I want the default --help to be as short as it was. This is way to verbose for -?/--help
3. I'm (very) open to using this as a --man/--manual/--info option
4. The text part of -o is missing a closing paren
5. CSVFILE should be CSV-file and XLSFILE should be XLS-file

Acceptable compromise?

**Comment by happy-barney** [comment]
I have no problem with that

**Comment by Tux** [comment]
Then go for it. If I am happy, I'll merge.
Any other suggestions?

**Comment by happy-barney** [comment]
@Tux are you happy with last changes? or still something to improve?

**Comment by Tux** [comment]
Sorry for the delay. I've done https://github.com/Tux/Spreadsheet-Read/commit/da8b031dddf44f71e44c83d5a7bbe56f82d6bc25 using your suggested help as base. I found too many things in pod2usage for the basic usage annoying to also use it for --help.
Thanks for your interest and help and feedback.
I will release soon.

**Pull request closed without merging**
