### PR TITLE
Add Spreadsheet::ReadGnumeric 0.1 support

### PR DESCRIPTION
**Pull request by rgrjr**
* Read.pm:
   + (_txt_is_xml):  New helper, looks for XML with an optional NS URI.
   + (ReadData):  Add a Gnumeric parser.
   + No documentation changes yet.
* t/700_gnumeric.t (added):
   + Gnumeric parsing tests.
* files/gnumeric.xml (added), files/gnumeric.gnumeric (added):
   + Gnumeric parsing data.
* MANIFEST:
   + Update.

### CODE REVIEW

**Comment by rgrjr** [comment]
You will notice that I've made no documentation changes.  I wanted to get a thumbs-up on the code first.

**Comment by Tux** [comment]
I have marked the mail as todo this week. $work load is high.
I seriously appreciate this work and promise to get back on it ASAP

**Comment by Tux** [comment]
Merged, but expect a change to fix the format "flaws"

**Comment by Tux** [comment]
I found https://cpan.metacpan.org/authors/id/R/RG/RGRJR/Spreadsheet-ReadGnumeric-0.1-TRIAL.tar.gz and installed that

The OO interface is not working (yet?)
```
    $book = Spreadsheet::Read->new ($source, @options);
    ok ($book,				"OO have gnumeric book");
    is (scalar $book->sheets, 3,	"OO book has 3 sheets");
```

→

```
Can't use an undefined value as a HASH reference at /data/pro/3gl/CPAN/Spreadsheet-Read/blib/lib/Spreadsheet/Read.pm line 251.
```

I'll commit my changes and extended test. Just pull and test

**Comment by rgrjr** [comment]
From: "H.Merijn Brand" <notifications@github.com>
   Date: Wed, 18 Jan 2023 08:45:47 -0800

   I found https://cpan.metacpan.org/authors/id/R/RG/RGRJR/Spreadsheet-ReadGnumeric-0.1-TRIAL.tar.gz and installed that

   The OO interface is not working (yet?)

There is no OO interface ATM.  To get the code working, I did the eqivalent of saving bank-statement.gnumeric as bank-statement.xlsx, using Spreadsheet::Read and Data::Dumper to show the data structure, and getting Spreadsheet::ReadGnumeric to produce something that looked as close as it could.  Since there were no objects in the Excel result, I put none in the Gnumeric return value.

					-- Bob

**Comment by Tux** [comment]
The OO interface is 100% integrated in Spreadsheet::Read. In theory the underlying parser should not be aware.

The design is such that Functional/OO API is completely transparant. If this does not work in Gnumeric, it might be a bug in S::R

**Comment by rgrjr** [comment]
From: "H.Merijn Brand" ***@***.***>
   Date: Thu, 19 Jan 2023 00:28:01 -0800

   The OO interface is 100% integrated in Spreadsheet::Read. In theory
   the underlying parser should not be aware.

OK.  I confess I wasn't able to figure this out based on a quick scan of
the code/doc.

   The design is such that Functional/OO API is completely transparant.
   If this does not work in Gnumeric, it might be a bug in S::R

If so, you might also want to look at Spreadsheet::ParseXLSX, since that
too is not producing blessed data structures from S::R.

   In any case, let me know if you need anything changed in
Spreadsheet::ReadGnumeric to help support OO from S::R.

					-- Bob

**Comment by rgrjr** [comment]
From: Bob Rogers ***@***.***>
   Date: Thu, 19 Jan 2023 12:20:37 -0800

   . . .

   If so, you might also want to look at Spreadsheet::ParseXLSX, since that
   too is not producing blessed data structures from S::R.

If it helps, I can submit a bug report to the issue tracker with a test
case.

					-- Bob

**Comment by Tux** [comment]
Yes please

**Comment by Tux** [comment]
Oh, do you have an example of code where it does *not* work? I thought I covered the OO interface in my tests, so if you state that it doesn't work, my tests might be incomplete

**Comment by rgrjr** [comment]
From: "H.Merijn Brand" ***@***.***>
   Date: Fri, 20 Jan 2023 01:51:59 -0800

   Oh, do you have an example of code where it does *not* work?  I
   thought I covered the OO interface in my tests, so if you state that
   it doesn't work, my tests might be incomplete

After taking a closer look, I see that the problem you are seeing is my
bug and has nothing to do with OO; I haven't completely supplied the
data structure that the "sheets" method expects.  I have committed a fix
to master at https://git.sr.ht/~rgrjr/Spreadsheet-ReadGnumeric; you
might want to start testing from that until you are satisfied that
ReadGnumeric is good to go.

   Once I fix this, only the stream OO tests were failing.  This turned
out to be because the "new" method was given the same stream that the
non-OO tests had used, so it was already at EOF, so of course it failed.
This can be fixed by splitting out the OO tests; I did so in a
straightforward way, which makes all of your new tests pass, and created
another pull request.

					-- Bob

**Comment by Tux** [comment]
On Fri, 20 Jan 2023 16:21:06 -0800, Bob Rogers ***@***.***> wrote:

>    From: "H.Merijn Brand" ***@***.***>
>    Date: Fri, 20 Jan 2023 01:51:59 -0800
> 
>    Oh, do you have an example of code where it does *not* work?  I
>    thought I covered the OO interface in my tests, so if you state that
>    it doesn't work, my tests might be incomplete
> 
> After taking a closer look, I see that the problem you are seeing is my
> bug and has nothing to do with OO; I haven't completely supplied the
> data structure that the "sheets" method expects.  I have committed a fix
> to master at https://git.sr.ht/~rgrjr/Spreadsheet-ReadGnumeric; you
> might want to start testing from that until you are satisfied that
> ReadGnumeric is good to go.

Done. Please state this "source" in your documentation, and preferably
in the META-data section "resources"

I am not a dzil user, so I have no idea where to set that, but
currently `Spreadsheet-ReadGnumeric-0.1/META.yml` does not yet include
it after build

Maybe I miss something, but after

 $ dzil install

Spreadsheet::Read's test starts failing with

t/700_gnumeric.t .. 1/? # Parser: Spreadsheet::ReadGnumeric-0.1
Can't locate object method "parse" via package "Spreadsheet::ReadGnumeric" at /data/pro/3gl/CPAN/Spreadsheet-Read/blib/lib/Spreadsheet/Read.pm line 1241.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
t/700_gnumeric.t .. Dubious, test returned 255 (wstat 65280, 0xff00)

which is *after* your PR

>    Once I fix this, only the stream OO tests were failing.  This turned
> out to be because the "new" method was given the same stream that the
> non-OO tests had used, so it was already at EOF, so of course it failed.
> This can be fixed by splitting out the OO tests; I did so in a
> straightforward way, which makes all of your new tests pass, and created
> another pull request.
> 
> 					-- Bob

-- 
H.Merijn Brand  https://tux.nl   Perl Monger   http://amsterdam.pm.org/
using perl5.00307 .. 5.37        porting perl5 on HP-UX, AIX, and Linux
https://tux.nl/email.html http://qa.perl.org https://www.test-smoke.org

**Comment by rgrjr** [comment]
From: "H.Merijn Brand" ***@***.***>
   Date: Sun, 22 Jan 2023 02:17:19 -0800

   On Fri, 20 Jan 2023 16:21:06 -0800, Bob Rogers ***@***.***> wrote:

   > After taking a closer look, I see that the problem you are seeing is my
   > bug and has nothing to do with OO; I haven't completely supplied the
   > data structure that the "sheets" method expects.  I have committed a fix
   > to master at https://git.sr.ht/~rgrjr/Spreadsheet-ReadGnumeric; you
   > might want to start testing from that until you are satisfied that
   > ReadGnumeric is good to go.

   Done. Please state this "source" in your documentation, and preferably
   in the META-data section "resources"

   I am not a dzil user, so I have no idea where to set that, but
   currently `Spreadsheet-ReadGnumeric-0.1/META.yml` does not yet include
   it after build

Yes, I am still learning it myself.  Filling in the repo location is on
my todo list.

   Maybe I miss something, but after

    $ dzil install

   Spreadsheet::Read's test starts failing . . .

   which is *after* your PR

If ReadGnumeric.pm exists but has no "parse" method, then that suggests
that "dzil install" has installed an old version, which is really odd.
I've been adding "-I.../Spreadsheet-ReadGnumeric/lib" to PERL5OPT for
testing, which may be easier at this point than figuring out where "dzil
install" is going wrong.

					-- Bob

**Pull request merged**
